name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases branches

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci
      - run: find ./scripts -type f -exec "shellcheck" "-x" {} \;
      - run: docker build -t semanticrelease/npm-registry-docker .
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
