name: Release
"on":
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: find ./scripts -type f -exec "shellcheck" "-x" {} \;
      - run: docker build -t semanticrelease/npm-registry-docker .
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
